package ibanlib

// CountrySpecificStructure contains length for IBAN and format for BBAN
type countrySpecificStructure struct {
	// IBAN Length
	Length int

	// BBAN regex
	BBANFormat string
}

var countries = map[string]countrySpecificStructure{
	"AD": countrySpecificStructure{Length: 24, BBANFormat: `^\d{4}\d{4}[A-Z0-9]{12}$`},
	"AE": countrySpecificStructure{Length: 23, BBANFormat: `^\d{3}\d{16}$`},
	"AL": countrySpecificStructure{Length: 28, BBANFormat: `^\d{8}[A-Z0-9]{16}$`},
	"AT": countrySpecificStructure{Length: 20, BBANFormat: `^\d{5}\d{11}$`},
	"AZ": countrySpecificStructure{Length: 28, BBANFormat: `^[A-Z]{4}[A-Z0-9]{20}$`},
	"BA": countrySpecificStructure{Length: 20, BBANFormat: `^\d{3}\d{3}\d{8}\d{2}$`},
	"BE": countrySpecificStructure{Length: 16, BBANFormat: `^\d{3}\d{7}\d{2}$`},
	"BG": countrySpecificStructure{Length: 22, BBANFormat: `^[A-Z]{4}\d{4}\d{2}[A-Z0-9]{8}$`},
	"BH": countrySpecificStructure{Length: 22, BBANFormat: `^[A-Z]{4}[A-Z0-9]{14}$`},
	"BR": countrySpecificStructure{Length: 29, BBANFormat: `^\d{8}\d{5}\d{10}[A-Z]{1}[A-Z0-9]{1}$`},
	"CH": countrySpecificStructure{Length: 21, BBANFormat: `^\d{5}[A-Z0-9]{12}$`},
	"CR": countrySpecificStructure{Length: 21, BBANFormat: `^\d{3}\d{14}$`},
	"CY": countrySpecificStructure{Length: 28, BBANFormat: `^\d{3}\d{5}[A-Z0-9]{16}$`},
	"CZ": countrySpecificStructure{Length: 24, BBANFormat: `^\d{4}\d{6}\d{10}$`},
	"DE": countrySpecificStructure{Length: 22, BBANFormat: `^\d{8}\d{10}$`},
	"DK": countrySpecificStructure{Length: 18, BBANFormat: `^\d{4}\d{9}\d{1}$`},
	"DO": countrySpecificStructure{Length: 28, BBANFormat: `^[A-Z]{4}\d{20}$`},
	"EE": countrySpecificStructure{Length: 20, BBANFormat: `^\d{2}\d{2}\d{11}\d{1}$`},
	"ES": countrySpecificStructure{Length: 24, BBANFormat: `^\d{4}\d{4}\d{1}\d{1}\d{10}$`},
	"FI": countrySpecificStructure{Length: 18, BBANFormat: `^\d{6}\d{7}\d{1}$`},
	"FO": countrySpecificStructure{Length: 18, BBANFormat: `^\d{4}\d{9}\d{1}$`},
	"FR": countrySpecificStructure{Length: 27, BBANFormat: `^\d{5}\d{5}[A-Z0-9]{11}\d{2}$`},
	"GB": countrySpecificStructure{Length: 22, BBANFormat: `^[A-Z]{4}\d{6}\d{8}$`},
	"GE": countrySpecificStructure{Length: 22, BBANFormat: `^[A-Z]{2}\d{16}$`},
	"GI": countrySpecificStructure{Length: 23, BBANFormat: `^[A-Z]{4}[A-Z0-9]{15}$`},
	"GL": countrySpecificStructure{Length: 18, BBANFormat: `^\d{4}\d{9}\d{1}$`},
	"GR": countrySpecificStructure{Length: 27, BBANFormat: `^\d{3}\d{4}[A-Z0-9]{16}$`},
	"GT": countrySpecificStructure{Length: 28, BBANFormat: `^[A-Z0-9]{4}[A-Z0-9]{20}$`},
	"HR": countrySpecificStructure{Length: 21, BBANFormat: `^\d{7}\d{10}$`},
	"HU": countrySpecificStructure{Length: 28, BBANFormat: `^\d{3}\d{4}\d{1}\d{15}\d{1}$`},
	"IE": countrySpecificStructure{Length: 22, BBANFormat: `^[A-Z]{4}\d{6}\d{8}$`},
	"IL": countrySpecificStructure{Length: 23, BBANFormat: `^\d{3}\d{3}\d{13}$`},
	"IS": countrySpecificStructure{Length: 26, BBANFormat: `^\d{4}\d{2}\d{6}\d{10}$`},
	"IT": countrySpecificStructure{Length: 27, BBANFormat: `^[A-Z]{1}\d{5}\d{5}[A-Z0-9]{12}$`},
	"JO": countrySpecificStructure{Length: 30, BBANFormat: `^[A-Z]{4}\d{4}[A-Z0-9]{18}$`},
	"KW": countrySpecificStructure{Length: 30, BBANFormat: `^[A-Z]{4}[A-Z0-9]{22}$`},
	"KZ": countrySpecificStructure{Length: 20, BBANFormat: `^\d{3}[A-Z0-9]{13}$`},
	"LB": countrySpecificStructure{Length: 28, BBANFormat: `^\d{4}[A-Z0-9]{20}$`},
	"LC": countrySpecificStructure{Length: 32, BBANFormat: `^[A-Z]{4}[A-Z0-9]{24}$`},
	"LI": countrySpecificStructure{Length: 21, BBANFormat: `^\d{5}[A-Z0-9]{12}$`},
	"LT": countrySpecificStructure{Length: 20, BBANFormat: `^\d{5}\d{11}$`},
	"LU": countrySpecificStructure{Length: 20, BBANFormat: `^\d{3}[A-Z0-9]{13}$`},
	"LV": countrySpecificStructure{Length: 21, BBANFormat: `^[A-Z]{4}[A-Z0-9]{13}$`},
	"MC": countrySpecificStructure{Length: 27, BBANFormat: `^\d{5}\d{5}[A-Z0-9]{11}\d{2}$`},
	"MD": countrySpecificStructure{Length: 24, BBANFormat: `^[A-Z0-9]{20}$`},
	"ME": countrySpecificStructure{Length: 22, BBANFormat: `^\d{3}\d{13}\d{2}$`},
	"MK": countrySpecificStructure{Length: 19, BBANFormat: `^\d{3}[A-Z0-9]{10}\d{2}$`},
	"MR": countrySpecificStructure{Length: 27, BBANFormat: `^\d{5}\d{5}\d{11}\d{2}$`},
	"MT": countrySpecificStructure{Length: 31, BBANFormat: `^[A-Z]{4}\d{5}[A-Z0-9]{18}$`},
	"MU": countrySpecificStructure{Length: 30, BBANFormat: `^[A-Z]{4}\d{2}\d{2}\d{12}\d{3}[A-Z]{3}$`},
	"NL": countrySpecificStructure{Length: 18, BBANFormat: `^[A-Z]{4}\d{10}$`},
	"NO": countrySpecificStructure{Length: 15, BBANFormat: `^\d{4}\d{6}\d{1}$`},
	"PK": countrySpecificStructure{Length: 24, BBANFormat: `^[A-Z]{4}[A-Z0-9]{16}$`},
	"PL": countrySpecificStructure{Length: 28, BBANFormat: `^\d{8}\d{16}$`},
	"PS": countrySpecificStructure{Length: 29, BBANFormat: `^[A-Z]{4}[A-Z0-9]{21}$`},
	"PT": countrySpecificStructure{Length: 25, BBANFormat: `^\d{4}\d{4}\d{11}\d{2}$`},
	"QA": countrySpecificStructure{Length: 29, BBANFormat: `^[A-Z]{4}[A-Z0-9]{21}$`},
	"RO": countrySpecificStructure{Length: 24, BBANFormat: `^[A-Z]{4}[A-Z0-9]{16}$`},
	"RS": countrySpecificStructure{Length: 22, BBANFormat: `^\d{3}\d{13}\d{2}$`},
	"SA": countrySpecificStructure{Length: 24, BBANFormat: `^\d{2}[A-Z0-9]{18}$`},
	"SC": countrySpecificStructure{Length: 31, BBANFormat: `^[A-Z]{4}\d{2}\d{2}\d{16}[A-Z]{3}$`},
	"SE": countrySpecificStructure{Length: 24, BBANFormat: `^\d{3}\d{16}\d{1}$`},
	"SI": countrySpecificStructure{Length: 19, BBANFormat: `^\d{5}\d{8}\d{2}$`},
	"SK": countrySpecificStructure{Length: 24, BBANFormat: `^\d{4}\d{6}\d{10}$`},
	"SM": countrySpecificStructure{Length: 27, BBANFormat: `^[A-Z]{1}\d{5}\d{5}[A-Z0-9]{12}$`},
	"ST": countrySpecificStructure{Length: 25, BBANFormat: `^\d{8}\d{11}\d{2}$`},
	"TL": countrySpecificStructure{Length: 23, BBANFormat: `^\d{3}\d{14}\d{2}$`},
	"TN": countrySpecificStructure{Length: 24, BBANFormat: `^\d{2}\d{3}\d{13}\d{2}$`},
	"TR": countrySpecificStructure{Length: 26, BBANFormat: `^\d{5}[A-Z0-9]{1}[A-Z0-9]{16}$`},
	"UA": countrySpecificStructure{Length: 29, BBANFormat: `^\d{6}[A-Z0-9]{19}$`},
	"VG": countrySpecificStructure{Length: 24, BBANFormat: `^[A-Z]{4}\d{16}$`},
	"XK": countrySpecificStructure{Length: 20, BBANFormat: `^\d{4}\d{10}\d{2}$`},
}
